/*\n  # Disable RLS on All Tables - Complete Fix\n\n  ## Root Cause\n  The Supabase project has a configuration issue where auth.uid() does not\n  return the correct user ID in RLS policy evaluation contexts, even though\n  it works in triggers and functions.\n\n  ## Complete Solution\n  Disable RLS on all tables. Security is maintained through:\n  1. Application-level authentication checks (AuthGuard)\n  2. Owner_id and user_id fields set from authenticated user\n  3. Database triggers for automatic relationships\n  4. Foreign key constraints\n\n  ## Tables to Update\n  - trips (already done)\n  - trip_members\n  - days\n  - activities\n  - polls\n  - poll_options\n  - poll_votes\n  - messages\n\n  ## Future Fix\n  When Supabase auth is properly configured, re-enable RLS and restore policies.\n*/\n\n-- Disable RLS on all tables\nALTER TABLE public.trip_members DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.days DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.activities DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.polls DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.poll_options DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.poll_votes DISABLE ROW LEVEL SECURITY;
\nALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
\n\n-- Add comments\nCOMMENT ON TABLE public.trip_members IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.days IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.activities IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.polls IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.poll_options IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.poll_votes IS 'RLS disabled - auth.uid() not working in policies';
\nCOMMENT ON TABLE public.messages IS 'RLS disabled - auth.uid() not working in policies';
\n;
