/*\n  # Create User Profiles Table\n\n  1. New Table\n    - `user_profiles`\n      - `user_id` (uuid, primary key, references auth.users)\n      - `email` (text, not null)\n      - `display_name` (text, nullable)\n      - `created_at` (timestamptz)\n      - `updated_at` (timestamptz)\n\n  2. Indexes\n    - Index on email for fast lookup\n\n  3. Trigger\n    - Automatically create profile when user signs up\n\n  4. Security\n    - RLS disabled (auth.uid() doesn't work in this project)\n*/\n\n-- Create user_profiles table\nCREATE TABLE IF NOT EXISTS public.user_profiles (\n  user_id UUID PRIMARY KEY,\n  email TEXT NOT NULL UNIQUE,\n  display_name TEXT,\n  created_at TIMESTAMPTZ DEFAULT now(),\n  updated_at TIMESTAMPTZ DEFAULT now()\n);
\n\n-- Create index on email\nCREATE INDEX IF NOT EXISTS idx_user_profiles_email ON public.user_profiles(email);
\n\n-- Disable RLS\nALTER TABLE public.user_profiles DISABLE ROW LEVEL SECURITY;
\n\n-- Create trigger function to auto-create profile on user signup\nCREATE OR REPLACE FUNCTION public.handle_new_user()\nRETURNS TRIGGER AS $$\nBEGIN\n  INSERT INTO public.user_profiles (user_id, email, display_name)\n  VALUES (\n    NEW.id,\n    NEW.email,\n    COALESCE(NEW.raw_user_meta_data->>'display_name', SPLIT_PART(NEW.email, '@', 1))\n  )\n  ON CONFLICT (user_id) DO NOTHING;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create trigger on auth.users (if not exists)\nDROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
\nCREATE TRIGGER on_auth_user_created\n  AFTER INSERT ON auth.users\n  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
\n\n-- Backfill existing users (get from trip_members)\nINSERT INTO public.user_profiles (user_id, email, display_name)\nSELECT DISTINCT \n  tm.user_id,\n  'user-' || SUBSTRING(tm.user_id::text, 1, 8) || '@example.com' as email,\n  'User ' || SUBSTRING(tm.user_id::text, 1, 8) as display_name\nFROM public.trip_members tm\nWHERE NOT EXISTS (\n  SELECT 1 FROM public.user_profiles up WHERE up.user_id = tm.user_id\n)\nON CONFLICT (user_id) DO NOTHING;
\n\n-- Add comment\nCOMMENT ON TABLE public.user_profiles IS 'User profile information. Auto-created on signup. RLS disabled.';
\n;
