/*\n  # Add Coordinates to Trips\n\n  1. Changes to trips table\n    - Add `lat` (numeric, nullable) - Latitude coordinate\n    - Add `lng` (numeric, nullable) - Longitude coordinate\n    - Add `place_id` (text, nullable) - Google Places ID for destination\n\n  2. Notes\n    - These fields are optional for backwards compatibility\n    - Coordinates enable map functionality\n    - place_id allows for place detail lookups\n*/\n\n-- Add lat column for latitude\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'trips' AND column_name = 'lat'\n  ) THEN\n    ALTER TABLE public.trips ADD COLUMN lat NUMERIC(10, 7);
\n  END IF;
\nEND $$;
\n\n-- Add lng column for longitude\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'trips' AND column_name = 'lng'\n  ) THEN\n    ALTER TABLE public.trips ADD COLUMN lng NUMERIC(10, 7);
\n  END IF;
\nEND $$;
\n\n-- Add place_id column for Google Places\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'trips' AND column_name = 'place_id'\n  ) THEN\n    ALTER TABLE public.trips ADD COLUMN place_id TEXT;
\n  END IF;
\nEND $$;
\n\n-- Add comments\nCOMMENT ON COLUMN public.trips.lat IS 'Latitude coordinate of destination (optional)';
\nCOMMENT ON COLUMN public.trips.lng IS 'Longitude coordinate of destination (optional)';
\nCOMMENT ON COLUMN public.trips.place_id IS 'Google Places ID for destination (optional)';
\n;
