/*\n  # Fix Trips Insert Policy and Auto-add Owner as Member\n\n  ## Problem\n  auth.uid() is not working correctly in RLS policies when using the anon key\n  from the browser, even for authenticated users.\n\n  ## Root Cause\n  When using createClient with the anon key, the JWT token might not have\n  the proper claims for auth.uid() to work in RLS policies.\n\n  ## Solution\n  1. Create a database function that inserts trips AND adds the owner as a member\n  2. Make RLS policy permissive for this specific function\n  3. Use SECURITY DEFINER to bypass RLS during the insert\n\n  ## Changes\n  1. Create function: create_trip_with_member(...)\n  2. This function will:\n     - Insert the trip\n     - Automatically add owner as 'organizer' in trip_members\n     - Return the created trip\n  3. Grant execute permission to anon and authenticated\n*/\n\n-- Drop the debug policy\nDROP POLICY IF EXISTS "debug_authenticated_can_insert_trips" ON public.trips;
\n\n-- Create a function to insert trip and add owner as member\nCREATE OR REPLACE FUNCTION public.create_trip_with_member(\n  p_title TEXT,\n  p_destination TEXT DEFAULT NULL,\n  p_start_date DATE DEFAULT NULL,\n  p_end_date DATE DEFAULT NULL\n)\nRETURNS TABLE (\n  id UUID,\n  owner_id UUID,\n  title TEXT,\n  destination TEXT,\n  start_date DATE,\n  end_date DATE,\n  created_at TIMESTAMPTZ\n)\nSECURITY DEFINER\nSET search_path = public\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  v_user_id UUID;
\n  v_trip_id UUID;
\nBEGIN\n  -- Get the authenticated user's ID\n  v_user_id := auth.uid();
\n  \n  -- Check if user is authenticated\n  IF v_user_id IS NULL THEN\n    RAISE EXCEPTION 'Not authenticated';
\n  END IF;
\n\n  -- Insert the trip\n  INSERT INTO public.trips (owner_id, title, destination, start_date, end_date)\n  VALUES (v_user_id, p_title, p_destination, p_start_date, p_end_date)\n  RETURNING trips.id INTO v_trip_id;
\n\n  -- Add owner as organizer in trip_members\n  INSERT INTO public.trip_members (trip_id, user_id, role)\n  VALUES (v_trip_id, v_user_id, 'organizer');
\n\n  -- Return the created trip\n  RETURN QUERY\n  SELECT t.id, t.owner_id, t.title, t.destination, t.start_date, t.end_date, t.created_at\n  FROM public.trips t\n  WHERE t.id = v_trip_id;
\nEND;
\n$$;
\n\n-- Grant execute permission to anon and authenticated roles\nGRANT EXECUTE ON FUNCTION public.create_trip_with_member TO anon;
\nGRANT EXECUTE ON FUNCTION public.create_trip_with_member TO authenticated;
\n\n-- Add comment\nCOMMENT ON FUNCTION public.create_trip_with_member IS \n  'Creates a new trip and automatically adds the owner as an organizer member. Uses SECURITY DEFINER to bypass RLS.';
\n;
