/*\n  # Add Foreign Keys to User Profiles\n\n  1. Changes\n    - Add foreign key from messages.author_id to user_profiles.user_id\n    - Add foreign key from trip_members.user_id to user_profiles.user_id (if not exists)\n    - Add foreign key from polls.created_by to user_profiles.user_id\n    - Add foreign key from poll_votes.user_id to user_profiles.user_id\n    - Add foreign key from trip_invitations.invited_by to user_profiles.user_id\n\n  2. Notes\n    - This enables JOIN queries to get user profile information\n    - Uses ON DELETE CASCADE to clean up when users are deleted\n*/\n\n-- Add foreign key for messages.author_id\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'messages_author_id_fkey'\n  ) THEN\n    ALTER TABLE public.messages \n    ADD CONSTRAINT messages_author_id_fkey \n    FOREIGN KEY (author_id) \n    REFERENCES public.user_profiles(user_id) \n    ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add foreign key for trip_members.user_id\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'trip_members_user_id_fkey'\n  ) THEN\n    ALTER TABLE public.trip_members \n    ADD CONSTRAINT trip_members_user_id_fkey \n    FOREIGN KEY (user_id) \n    REFERENCES public.user_profiles(user_id) \n    ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add foreign key for polls.created_by\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'polls_created_by_fkey'\n  ) THEN\n    ALTER TABLE public.polls \n    ADD CONSTRAINT polls_created_by_fkey \n    FOREIGN KEY (created_by) \n    REFERENCES public.user_profiles(user_id) \n    ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add foreign key for poll_votes.user_id\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'poll_votes_user_id_fkey'\n  ) THEN\n    ALTER TABLE public.poll_votes \n    ADD CONSTRAINT poll_votes_user_id_fkey \n    FOREIGN KEY (user_id) \n    REFERENCES public.user_profiles(user_id) \n    ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add foreign key for trip_invitations.invited_by\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints \n    WHERE constraint_name = 'trip_invitations_invited_by_fkey'\n  ) THEN\n    ALTER TABLE public.trip_invitations \n    ADD CONSTRAINT trip_invitations_invited_by_fkey \n    FOREIGN KEY (invited_by) \n    REFERENCES public.user_profiles(user_id) \n    ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add comments\nCOMMENT ON CONSTRAINT messages_author_id_fkey ON public.messages IS 'Links messages to user profiles';
\nCOMMENT ON CONSTRAINT trip_members_user_id_fkey ON public.trip_members IS 'Links trip members to user profiles';
\nCOMMENT ON CONSTRAINT polls_created_by_fkey ON public.polls IS 'Links polls to user who created them';
\nCOMMENT ON CONSTRAINT poll_votes_user_id_fkey ON public.poll_votes IS 'Links poll votes to users';
\nCOMMENT ON CONSTRAINT trip_invitations_invited_by_fkey ON public.trip_invitations IS 'Links invitations to user who sent them';
\n;
